### ISSUE TITLE
Use without the hotswap plates?

### ISSUE THREAD

**Issue by rzfzr** [strayer/taira-keyboard#6]
Firstly, thanks for sharing.
I already have the switches, no interest in using the plates, I notice from the pictures that it has unpadded holes, are those choc compatible? It's just a matter of 'tinning' the pads with KiCad ? or it's lacking the internal wiring for it? I'm a full noob in this custom pcb realm.
Thanks again

**Comment by strayer** [comment]
Hey @rzfzr. I'm assuming you are talking about the Kailh hotswap sockets? If you are going that route I'd recommend replacing the whole footprint in Kicad with one that is already prepared for directly soldering the switches. The traces will need to be retraced too, as they are then hanging in the air. Although that shouldn't be that difficult since the hotswap socket pads are pretty much in the same area as the switch contact legs are.

**Comment by rzfzr** [comment]
Cool,
If I end up going that route I'll make sure to link it.
the hot swap sockets are cheap enough that I might just go with that instead though.
Thanks

**Comment by strayer** [comment]
I had to remove some switches from my Ergodash and swore to NEVER solder a switch to a PCB ever again :D That's why I went with mandatory hotswap sockets. As you said, they are not that expensive and if you actually need to remove a switch (I played around with different Choc variants for example), it makes your life much easier.
